### ISSUE TITLE
아이디어 제시합니다.

### ISSUE THREAD

**Issue by ESTAID** [nghy97/small-stockholders#3]
소주주 종목을 설정하고 증권사 API를 사용하여 종목 정보를 얻습니다. 
그리고 매수, 매도 금액을 설정하고 해당 금액에 도달했을 때 슬랙 or 크롬 노티로 알려주는 어플리케이션이 있으면 좋겠습니다.

편하게 의견주시면 감사하겠습니다.

**Comment by nghy97** [comment]
매도 금액 설정해 알람이 와서 확인했는데,
이미 그 금액보다 더 많거나 적을 수도 있습니다. 정확한 정보라고 할 수 있을까요?

지금같은 주식판에서는 0.1초, 1초마다 변동이 심합니다.

**Comment by ESTAID** [comment]
그 생각을 못했네요. nghy97님 말대로 지금 같은 주식판엔 어울리지 못한 아이디어같습니다.

**Comment by nghy97** [comment]
고맙습니다. 이슈 닫겠습니다.
